---
name: Release

# yamllint disable-line rule:truthy
on:
  release:
    types:
      - published
  workflow_dispatch:

permissions:
  contents: write

jobs:
  release:
    uses: timmo001/workflows/.github/workflows/ha-card-release.yml@6391eb6416fc711a5d6c1c96b6b4a4b8c16af5af # master
    permissions:
      contents: write
