---
name: HACS Validate

# yamllint disable-line rule:truthy
on:
  pull_request:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  validate:
    uses: timmo001/workflows/.github/workflows/ha-card-validate.yml@fe592e0a559dc882914a1f21c8af7fee5362cb11 # master
